"""empty message

Revision ID: 1fb649f78797
Revises: 5ca4adc11b64
Create Date: 2017-07-09 17:40:40.269655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb649f78797'
down_revision = '5ca4adc11b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
