"""empty message

Revision ID: 880ab3963c44
Revises: bbc7df84cdea
Create Date: 2017-08-22 18:18:20.076862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880ab3963c44'
down_revision = 'bbc7df84cdea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_up', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_up')
    # ### end Alembic commands ###
