"""empty message

Revision ID: f24c0b4df990
Revises: 1fb649f78797
Create Date: 2017-07-13 21:47:04.925972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f24c0b4df990'
down_revision = '1fb649f78797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('posts_ibfk_2', 'posts', type_='foreignkey')
    op.drop_column('posts', 'type_id')
    op.drop_table('types')
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.create_foreign_key('posts_ibfk_2', 'posts', 'types', ['type_id'], ['id'])
    # op.drop_column('posts', 'category_id')
    # op.create_table('types',
    # sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    # sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    # sa.Column('label', mysql.VARCHAR(length=128), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_default_charset='utf8',
    # mysql_engine='InnoDB'
    # )
    op.drop_table('categories')
    # ### end Alembic commands ###
