"""empty message

Revision ID: bbc7df84cdea
Revises: ba68895c4554
Create Date: 2017-08-22 17:30:07.815026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc7df84cdea'
down_revision = 'ba68895c4554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('last_edit', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_last_edit'), 'posts', ['last_edit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_last_edit'), table_name='posts')
    op.drop_column('posts', 'last_edit')
    # ### end Alembic commands ###
